name: turon-ai-frontend

services:
  frontend:
    container_name: turon-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ""
    restart: always
    ports:
      - "127.0.0.1:3001:3001"
    networks:
      - frontend_net

networks:
  frontend_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.250.0/24
