name: turon-ai-frontend

services:
  frontend:
    container_name: turon-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ""
    restart: always
    ports:
      - "127.0.0.1:3001:3001"