"""activity action and last_seen

Revision ID: 64c95b9291a9
Revises: e45ea80bbf17
Create Date: 2026-07-01 11:28:49.846237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "64c95b9291a9"
down_revision: Union[str, None] = "e45ea80bbf17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_messages", sa.Column("vote", sa.String(length=10), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_messages", "vote")
    # ### end Alembic commands ###
