"""activity action and last_seen

Revision ID: e45ea80bbf17
Revises: 558f7651ff29
Create Date: 2026-07-01 06:00:45.314364

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "e45ea80bbf17"
down_revision: Union[str, None] = "558f7651ff29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "login_events",
        sa.Column(
            "action",
            sa.String(length=20),
            server_default="login",
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_seen_at")
    op.drop_column("login_events", "action")
    # ### end Alembic commands ###
